services:
  internal-service-health-check-api:
    build: .
    ports:
      - 8080:8080
    environment:
      - WEB_HEALTH_HOST=1.1.1.1
      - WEB_HEALTH_PORT=53
      - WEB_HEALTH_TYPE=TCP
    restart: always