services:
  internal-service-health-check-api:
    build: .
    ports:
      - 8080:8080
    environment:
      - SINGLE_THREADED=true
      
      - WEB_HEALTH_HOST=example.com
      - WEB_HEALTH_PORT=80
      - WEB_HEALTH_TYPE=TCP

      - DNS_HEALTH_HOST=1.1.1.1
      - DNS_HEALTH_PORT=53
      - DNS_HEALTH_TYPE=TCP
    restart: always